/* Sample data for the Procurement War Room playground.
 *
 * Shipped as a .js file (loaded via <script src> from index.html;
 * CSP `script-src 'self'` allows that, `connect-src 'none'`
 * blocks fetch).
 *
 * 30 vendors × 10 agencies × 5 years (2020-2024) = up to 1,500
 * potential contract slots, populated SPARSELY (most vendors
 * only do business with 2-4 agencies). Numbers are SYNTHETIC,
 * generated by a deterministic PRNG so the dashboard is
 * byte-stable across builds. Vendor names use generic 示範-
 * prefixes so they can't be mistaken for real companies.
 *
 * Anomaly seeding: 3 vendors get a deliberate 8-10× YoY jump in
 * 2023→2024 contracts so the anomaly panel has signal to find.
 */

(function () {
	'use strict';

	var YEARS = [2020, 2021, 2022, 2023, 2024];

	var AGENCIES = [
		{ id: 'edu', name: '教育部' },
		{ id: 'mot', name: '交通部' },
		{ id: 'mnd', name: '國防部' },
		{ id: 'moi', name: '內政部' },
		{ id: 'mohw', name: '衛生福利部' },
		{ id: 'moea', name: '經濟部' },
		{ id: 'moj', name: '法務部' },
		{ id: 'mof', name: '財政部' },
		{ id: 'moc', name: '文化部' },
		{ id: 'moenv', name: '環境部' }
	];

	function vendorList() {
		var out = [];
		var prefixes = [
			{ prefix: '示範-工程', count: 10 },
			{ prefix: '示範-科技', count: 10 },
			{ prefix: '示範-服務', count: 10 }
		];
		var n = 0;
		for (var p = 0; p < prefixes.length; p += 1) {
			for (var i = 1; i <= prefixes[p].count; i += 1) {
				n += 1;
				var idx = i < 10 ? '00' + i : '0' + i;
				out.push({ id: 'v' + n, name: prefixes[p].prefix + '-' + idx });
			}
		}
		return out;
	}

	var VENDORS = vendorList();

	// PRNG with a fixed seed.
	var seed = 4242422;
	function rand() {
		seed = (seed * 9301 + 49297) % 233280;
		return seed / 233280;
	}

	// Anomaly-seed vendor ids (3 vendors get a deliberate 8-10x
	// jump in 2024 over 2023). Picked to be from different
	// vendor-name prefixes so the anomaly panel demonstrates the
	// pattern across categories.
	var ANOMALY_VENDORS = new Set(['v3', 'v15', 'v25']);

	function buildContracts() {
		var rows = [];
		for (var vi = 0; vi < VENDORS.length; vi += 1) {
			var v = VENDORS[vi];
			// Each vendor picks 2-4 agencies to do business with.
			var agencyCount = 2 + Math.floor(rand() * 3);
			var pickedAgencies = pickAgencies(agencyCount);
			// Per (vendor, agency), generate a 5-year contract
			// stream. Base scale per vendor varies an order of
			// magnitude.
			var baseScale = Math.pow(10, 6 + rand() * 2); // NT$1M – NT$100M-ish
			for (var ai = 0; ai < pickedAgencies.length; ai += 1) {
				var agency = pickedAgencies[ai];
				var agencyShare = 0.3 + rand() * 0.7;
				for (var yi = 0; yi < YEARS.length; yi += 1) {
					var year = YEARS[yi];
					var jitter = 0.7 + rand() * 0.6;
					var trend = 1 + (yi - 2) * 0.05; // small +/- around 2022
					var amount = Math.round(baseScale * agencyShare * jitter * trend);
					if (rand() < 0.15) amount = 0; // ~15 % of (vendor,agency,year) slots stay empty
					if (amount > 0) {
						rows.push({
							vendor_id: v.id,
							agency_id: agency.id,
							year: year,
							amount_ntd: amount
						});
					}
				}
			}
		}
		// Seed anomalies: for each anomaly vendor, pick their
		// largest 2023 row and 8-10x its 2024 counterpart.
		ANOMALY_VENDORS.forEach(function (vid) {
			// Find their 2023 max-amount row.
			var max2023 = null;
			for (var i = 0; i < rows.length; i += 1) {
				if (rows[i].vendor_id !== vid || rows[i].year !== 2023) continue;
				if (!max2023 || rows[i].amount_ntd > max2023.amount_ntd) max2023 = rows[i];
			}
			if (!max2023) return;
			// Find or create the matching 2024 row for the same
			// vendor + agency.
			var found = null;
			for (var j = 0; j < rows.length; j += 1) {
				if (
					rows[j].vendor_id === vid &&
					rows[j].agency_id === max2023.agency_id &&
					rows[j].year === 2024
				) {
					found = rows[j];
					break;
				}
			}
			var multiplier = 8 + Math.floor(rand() * 3); // 8x-10x
			var target = max2023.amount_ntd * multiplier;
			if (found) {
				found.amount_ntd = target;
			} else {
				rows.push({
					vendor_id: vid,
					agency_id: max2023.agency_id,
					year: 2024,
					amount_ntd: target
				});
			}
		});
		return rows;
	}

	function pickAgencies(count) {
		var pool = AGENCIES.slice();
		var out = [];
		for (var i = 0; i < count && pool.length > 0; i += 1) {
			var idx = Math.floor(rand() * pool.length);
			out.push(pool[idx]);
			pool.splice(idx, 1);
		}
		return out;
	}

	window.__PROCUREMENT_DATA__ = {
		_meta: {
			schema_version: 1,
			years: YEARS,
			anomaly_threshold_x: 5,
			'real_data_disclaimer_zh-TW':
				'廠商名稱(示範-工程-XX 等)與所有得標金額皆為遵循公開均值生成的合成樣本,並非真實採購紀錄。正式部署需連線至載入政府電子採購網資料的後端。',
			real_data_disclaimer_en:
				'Vendor names (`示範-工程-XX` etc.) and all award amounts are synthetic samples calibrated to public averages — NOT real procurement records. Production deployments must connect to a backend with the Government e-Procurement dataset loaded.'
		},
		vendors: VENDORS,
		agencies: AGENCIES,
		contracts: buildContracts()
	};
})();
